# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f9613348422927ec88f38acc102c0db1b8587d24177222b1cd90d0b7b785d0abb8031ca320768cf2990d69d3c463e959a4026bbbffbad6c8370ecc31f5d8c1

test:
  secret_key_base: b1b24872879af9c7116e6a5baca1a4cc51b9c3675f13cf0f81748e89ade5c4307e8992849ad9813ae2564844916c9e01beb97e60b33da3d7748bbaea6155ae57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
